/**
 * "Chambre des Paradoxes" engine.
 *
 * Mechanic: transform a line of colored glyphs into a target configuration
 * using a handful of reversible operations. The twist — paradoxes — periodically
 * rewrite what your controls do (mirror, inversion, freeze, shift). You earn
 * "énergie paradoxale" by making progress and spend it on temporary powers.
 *
 * Levels are generated by applying random reversible operations to the target,
 * which GUARANTEES a solution exists within the move budget (the inverse of the
 * generation sequence), satisfying robustness while staying procedurally
 * replayable. Paradoxes change controls but never remove reachability, and the
 * budget is generous enough to absorb them.
 */
import { Rng } from '../../lib/rng';

export type Difficulty = 'entrainement' | 'normal' | 'difficile' | 'cauchemar';

export type ParadoxKind = 'mirror' | 'inversion' | 'freeze' | 'shift';

export interface OpInc {
  type: 'inc' | 'dec';
  index: number;
}
export interface OpSwap {
  type: 'swap';
  index: number;
}
export interface OpRot {
  type: 'rot';
  dir: 'left' | 'right';
}
export type Op = OpInc | OpSwap | OpRot;

export interface Level {
  id: string;
  seed: string;
  difficulty: Difficulty;
  size: number;
  colors: number;
  start: number[];
  target: number[];
  budget: number;
  /** every `period` moves a paradox triggers */
  period: number;
  paradoxOrder: ParadoxKind[];
}

export interface PlayState {
  cells: number[];
  movesUsed: number;
  energy: number;
  minDistance: number;
  activeParadox: ParadoxKind | null;
  frozenCell: number | null;
  solved: boolean;
  failed: boolean;
}

const DIFF: Record<
  Difficulty,
  { size: number; colors: number; gen: number; slack: number; period: number }
> = {
  entrainement: { size: 4, colors: 3, gen: 4, slack: 10, period: 99 },
  normal: { size: 5, colors: 3, gen: 7, slack: 8, period: 5 },
  difficile: { size: 6, colors: 4, gen: 10, slack: 8, period: 4 },
  cauchemar: { size: 7, colors: 4, gen: 14, slack: 9, period: 3 },
};

/* ----------------------------- core ops ----------------------------- */

export function distance(a: number[], b: number[]): number {
  let d = 0;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) d++;
  return d;
}

function rotate(cells: number[], dir: 'left' | 'right'): number[] {
  const n = cells.length;
  if (dir === 'left') return [...cells.slice(1), cells[0]];
  return [cells[n - 1], ...cells.slice(0, n - 1)];
}

/** Apply a raw op (no paradox interpretation). Pure. */
export function applyRaw(cells: number[], op: Op, colors: number): number[] {
  const next = cells.slice();
  switch (op.type) {
    case 'inc':
      next[op.index] = (next[op.index] + 1) % colors;
      return next;
    case 'dec':
      next[op.index] = (next[op.index] + colors - 1) % colors;
      return next;
    case 'swap': {
      const j = (op.index + 1) % next.length;
      [next[op.index], next[j]] = [next[j], next[op.index]];
      return next;
    }
    case 'rot':
      return rotate(next, op.dir);
  }
}

/**
 * Translate a player's intended op into the effective op given the active
 * paradox (this is what makes "the rules change mid-game").
 */
export function interpret(op: Op, paradox: ParadoxKind | null, size: number): Op {
  if (!paradox) return op;
  switch (paradox) {
    case 'inversion':
      if (op.type === 'inc') return { type: 'dec', index: op.index };
      if (op.type === 'dec') return { type: 'inc', index: op.index };
      return op;
    case 'mirror':
      if (op.type === 'rot')
        return { type: 'rot', dir: op.dir === 'left' ? 'right' : 'left' };
      return op;
    case 'shift':
      // swaps reach one further (i and i+2)
      if (op.type === 'swap')
        return { type: 'swap', index: (op.index + 1) % size };
      return op;
    case 'freeze':
      return op; // freeze handled separately (blocks a cell)
  }
}

/* ---------------------------- generation ---------------------------- */

function randomOp(rng: Rng, size: number): Op {
  const roll = rng.int(0, 3);
  if (roll === 0) return { type: 'inc', index: rng.int(0, size - 1) };
  if (roll === 1) return { type: 'dec', index: rng.int(0, size - 1) };
  if (roll === 2) return { type: 'swap', index: rng.int(0, size - 1) };
  return { type: 'rot', dir: rng.chance(0.5) ? 'left' : 'right' };
}

export function generateLevel(
  seed: string,
  difficulty: Difficulty,
  index = 0,
): Level {
  const cfg = DIFF[difficulty];
  const rng = new Rng(`paradox:${seed}:${index}`);
  const size = cfg.size;
  const colors = cfg.colors;

  const target = Array.from({ length: size }, () => rng.int(0, colors - 1));

  // Apply gen random ops forward to derive the start; the inverse sequence is
  // a guaranteed solution, so the level is solvable within `gen` real moves.
  let cells = target.slice();
  const gen = cfg.gen + Math.min(index, 8); // escalate in infinite mode
  for (let k = 0; k < gen; k++) {
    cells = applyRaw(cells, randomOp(rng, size), colors);
  }
  // Ensure the puzzle isn't already solved.
  if (distance(cells, target) === 0) {
    cells = applyRaw(cells, { type: 'inc', index: 0 }, colors);
  }

  const paradoxKinds: ParadoxKind[] = ['mirror', 'inversion', 'shift', 'freeze'];
  const paradoxOrder =
    difficulty === 'entrainement' ? [] : rng.shuffle(paradoxKinds);

  return {
    id: `${seed}-${index}`,
    seed,
    difficulty,
    size,
    colors,
    start: cells,
    target,
    budget: gen + cfg.slack,
    period: cfg.period,
    paradoxOrder,
  };
}

/* ----------------------------- play ----------------------------- */

export function initialState(level: Level): PlayState {
  return {
    cells: level.start.slice(),
    movesUsed: 0,
    energy: 0,
    minDistance: distance(level.start, level.target),
    activeParadox: null,
    frozenCell: null,
    solved: false,
    failed: false,
  };
}

export interface MoveResult {
  state: PlayState;
  paradoxTriggered: ParadoxKind | null;
  gainedEnergy: boolean;
  blocked?: string;
}

/** Apply a player's move, then advance the paradox clock. Pure. */
export function play(level: Level, state: PlayState, op: Op): MoveResult {
  if (state.solved || state.failed) {
    return { state, paradoxTriggered: null, gainedEnergy: false };
  }
  // Frozen cell blocks inc/dec on it.
  if (
    state.frozenCell != null &&
    (op.type === 'inc' || op.type === 'dec') &&
    op.index === state.frozenCell
  ) {
    return {
      state,
      paradoxTriggered: null,
      gainedEnergy: false,
      blocked: 'Cette cellule est gelée par un paradoxe.',
    };
  }

  const effective = interpret(op, state.activeParadox, level.size);
  const cells = applyRaw(state.cells, effective, level.colors);
  const movesUsed = state.movesUsed + 1;
  const dist = distance(cells, level.target);

  let energy = state.energy;
  let gainedEnergy = false;
  if (dist < state.minDistance) {
    energy += 1;
    gainedEnergy = true;
  }
  const minDistance = Math.min(state.minDistance, dist);
  const solved = dist === 0;

  // Advance paradox clock.
  let activeParadox = state.activeParadox;
  let frozenCell = state.frozenCell;
  let paradoxTriggered: ParadoxKind | null = null;
  if (
    !solved &&
    level.paradoxOrder.length > 0 &&
    movesUsed % level.period === 0
  ) {
    const idx = Math.floor(movesUsed / level.period - 1) % level.paradoxOrder.length;
    paradoxTriggered = level.paradoxOrder[idx];
    if (paradoxTriggered === 'freeze') {
      activeParadox = null;
      frozenCell = (movesUsed * 7 + 3) % level.size;
    } else {
      activeParadox = paradoxTriggered;
      frozenCell = null;
    }
  }

  const failed = !solved && movesUsed >= level.budget;

  return {
    state: {
      cells,
      movesUsed,
      energy,
      minDistance,
      activeParadox,
      frozenCell,
      solved,
      failed,
    },
    paradoxTriggered,
    gainedEnergy,
  };
}

/* ----------------------------- powers ----------------------------- */

export type PowerId = 'stase' | 'revelation' | 'saut';

export const POWERS: Record<PowerId, { name: string; cost: number; desc: string }> = {
  revelation: { name: 'Révélation', cost: 1, desc: 'Met en évidence les cellules déjà correctes.' },
  stase: { name: 'Stase', cost: 2, desc: 'Annule le paradoxe actif et dégèle les cellules.' },
  saut: { name: 'Saut quantique', cost: 3, desc: 'Replace une cellule incorrecte sur sa bonne valeur.' },
};

export function usePower(
  level: Level,
  state: PlayState,
  power: PowerId,
): PlayState {
  if (state.energy < POWERS[power].cost) return state;
  const energy = state.energy - POWERS[power].cost;
  if (power === 'stase') {
    return { ...state, energy, activeParadox: null, frozenCell: null };
  }
  if (power === 'saut') {
    const cells = state.cells.slice();
    const wrong = cells.findIndex((c, i) => c !== level.target[i]);
    if (wrong === -1) return state;
    cells[wrong] = level.target[wrong];
    const dist = distance(cells, level.target);
    return {
      ...state,
      energy,
      cells,
      minDistance: Math.min(state.minDistance, dist),
      solved: dist === 0,
    };
  }
  // revelation is informational; just spend energy.
  return { ...state, energy };
}

/* ----------------------------- scoring ----------------------------- */

export function scoreLevel(
  level: Level,
  state: PlayState,
  elapsedSec: number,
): number {
  if (!state.solved) return 0;
  const diffMult = { entrainement: 0.5, normal: 1, difficile: 1.6, cauchemar: 2.3 }[
    level.difficulty
  ];
  const base = 200 * diffMult;
  const efficiency = Math.max(0, level.budget - state.movesUsed) * 15;
  const speed = Math.max(0, 120 - elapsedSec) * 2;
  return Math.round(base + efficiency + speed);
}
